version: '3.7'
services:
  adlacarte-history:
    image: docker.pkg.github.com/juliansauer/adlacartehistory/adlacarte-history:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: $PWD/credentials
        target: /credentials
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - adlacarte-history
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: $PWD/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: prometheus_storage
        target: /prometheus
    ports:
      - 9090:9090
    networks:
      - default
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=14d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
  grafana:
    image: grafana/grafana:6.5.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD:-admin}
    volumes:
      - type: volume
        source: grafana_storage
        target: /var/lib/grafana
    networks:
      - default
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  prometheus_storage:
  grafana_storage:
